#!/bin/sh
#===============================================================================
#
#          FILE: shtest
# 
#         USAGE: ./shtest 
# 
#   DESCRIPTION: testing script for various things, dont delete me yet!
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Dr. Fritz Mehner (fgm), mehner.fritz@fh-swf.de
#  ORGANIZATION: FH Südwestfalen, Iserlohn, Germany
#       CREATED: 02/09/2015 11:29
#      REVISION:  ---
#===============================================================================

DEFAULT_WT_TIMEOUT=12:24:36

if [ "$1" != "" ] && echo $1 | grep '^[0-9]{1,3}:[0-9]{2}:[0-9]{2}$' -Pq; then
	echo "timeout format verified ok"
else
	echo -n "timeout variable not in the format of [(hh)h:mm:ss]!  failing back to default: "
	set -- $DEFAULT_WT_TIMEOUT
	echo "$1"
fi

H=`echo $1 | grep -Po "^[0-9]{1,3}(?=:)"`
M=`echo $1 | grep -Po "(?<=:)[0-9]{2}(?=:)"`
S=`echo $1 | grep -Po "(?<=:)[0-9]{2}$"`


