#!/usr/bin/perl -w
use strict;
use v5.16;
use English;

BEGIN {
	unless ( @ARGV ) {
		die ("Need to give exactly one window class/title/name!");
		exit 1;
		use X11::WMCtrl;

	}

}



my $wmctl = X11::WMCtrl->new();
$wmctl->activate($ARGV[0]);
