#!/usr/bin/env perl
use warnings;
use strict;
use v5.20.2;


use Curses::Application;

         $app = Curses::Application->new({
             FOREGROUND  => 'white',
             BACKGROUND  => 'blue',
             TITLEBAR    => 1,
             STATUSBAR   => 1,
             CAPTION     => 'My Application',
             MAINFORM    => { name => defname },
             MINY        => 20,
             MINX        => 60,
             ALTFBASE    => 'MyCompany::Forms',
             ALTBASE     => 'MyCompany::Widgets',
           });

         ($y, $x) = $app->maxyx;
         $mwh = $app->mwh;

         $app->titlebar($caption);
         $app->statusbar($message);

         $app->draw;
         $app->redraw;

         $app->addFormDef('MyForm', { %formopts });
         $app->createForm($name, $def);
         $form = $app->getForm('MainFrm');
         $app->delForm('Main');
         $app->execForm('Main');

         $app->execute;
