#!/bin/zsh
# vim ft=zsh:fen:fdm=marker:fmr={{{,}}}:fcl=all:fdo=insert:cc=80:sw=4:ts=4:noet:more:ruler:ls=2
#
#    dir2m3u
#    materialize m3u file(s) from subdirs with media in them
#    mini
#    eso/ubin-local
#
#    Copyright (C) 1995-2018 Gabriel Thomas Sharp
#
#    Written by Gabriel T. Sharp <21shariria@gmail.com>
#    Latest versions of this and all of my projects can be
#    obtained by visiting the repository: 
#
#    <https://github.com/osirisgothra>
#
#    Because of the global availability of github at this point, hosting
#    any additional servers for public use no longer serves a purpose. All
#    content is available 24/7 through github. (Thanks to GITHUB!).
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#    HISTORY
#
#	 Mon Apr 22 06:18:15 EDT 2019
#            osirisgothra@larnica initially created this file
#            with the original name, dir2m3u
#
#  (this header was created using the template generator by Gabriel T. Sharp)
#
#
#
for x in */; do 
	name=`echo $x | sed -r 's/[- \/0-9]+//g;s/^(.*)([A-Z]+[a-z]+)$/\l\2/g'`
	find "$x" -iname '*.mp3' | sed '1i#M3UEXT' > ${name}.m3u
	echo $x"^^"
done


