#!/usr/bin/perl
use warnings;
use strict;
use v5.20;
use Path::Tiny;
use Curses::UI;
use Getopt::Long::Descriptive;


my ($opt, $usage) = describe_options(
	'my-program %o <some-arg>',
	[ 'server|s=s', "the server to connect to", { required => 1  } ],
	[ 'port|p=i',   "the port to connect to",   { default  => 79 } ],
	[],
	[ 'debug|d=s', "debug to a logfile or /tmp/dlg.log if none is given", { required => 0, default => "/tmp/dlg.log"
	[ 'verbose|v',  "print extra stuff"            ],
	[ 'help',       "print usage message and exit" ],
	);	
	print($usage->text), exit if $opt->help;

	my $cui = Curses::UI->new( -clear_on_exit => 1,
	-debug => $opt->debug, );


$cui->mainloop;

