#!/usr/bin/perl

use v5.20.1;
use warnings;
use strict;
use Path::Tiny;
use Getopt::Long::Descriptive;
use File::Slurp;


use Getopt::Long::Descriptive; # opt|shortchar[kind] (kind is =s[tr],=i[nt], or none)
my ($opt, $usage) = describe_options(
        path($0)->basename() . ' %o <some-arg> file',
        [ 'no-dialog', "dont use dialog to show log", { required => 1  } ],
        [ 'no-follow',   "do not follow the log, just show it",   { default  => 79 } ],

        [],
        [ 'verbose|v',  "print extra stuff"            ],
        [ 'help',       "print usage message and exit" ],
		
      );

say($usage->text), exit if $opt->help;
