#!/bin/bash
#
#    fastgimp
#    run gimp without pattern or brush libraries
#    mini
#    eso-ubinlocal
#
#    Copyright (C) 1995-2021 Gabriel T. Sharp
#
#    Written by Gabriel T. Sharp <21shariria@gmail.com>
#    Latest versions of this and all projects can be
#    obtained by visiting the repository at:
#
#    <https://github.com/osirisgothra>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#    HISTORY
#
#	 Sat 10 Apr 2021 07:41:33 PM EDT
#            osirisgothra@ initially created this file
#            with the original name, fastgimp
#
#
#
#  This template and header was created using the template generator by Gabriel T. Sharp
#  You can download the latest version at: <https://www.github.com/osirisgothra/mini.git/eso/ubin-local/template>
#  (the url is subject to changes on github's behalf, please submit a pull request to fix or request a fix on any url changes)
#


# Get Options from Command Line for fastgimp

declare -ga opts
declare -gi quiet_level=0
declare -g version_text="$(tput setaf 124)fastgimp$(tput sgr0) Version 1.0 (C)2020 Gabriel T. Sharp, Licensed under GNU LGPL3 at https://gpl.gnu.org/gpl3.html"
declare -g help_text="fastgimp
run gimp without pattern or brush libraries

SYNTAX

	fastgimp [OPTIONS] FILES -- [GIMP ARGUMENTS]

OPTIONS
	--help -h	show this help text
 --version -v   display version information and exit (also shows license info)
   --quiet -q   increase quiet level by one (quiet level is always zero if left alone)

ARGUMENTS

	FILENAME	A filename that must exist or be writable by the current user.
	PATHNAME	A relative or absolute path that must exist or be creatable.
	STRING		A readable string, it must not contain any unreprintable characters.
	NUMBER		An integer, usually between -32767 and 32767.
	BOOLEAN		A true/false value, represented as 0 for false, and any other value for true.
	FLOAT		A floating point single or double precision value, it is precise down to about 5 ot 6 decimal places.
	ENG			Scientific notation, expressed in powers (3x10^4 is written as 3.4)
	DEG			Like GRAD/RAD, but expressed in degrees (hours, minutes, seconds) so 3 5'5\" is written as \"3.5.5\"


LICENSE

	GNU LGPL3 is available in full at the GNU GPL website, or through the google voice command 'show me GNU LGPL VERSION 3'

"
lecho() { builtin echo "$@"; }

echo() {
	if [[ $quiet_level -gt 0 ]]; then
		return 127
	else
		builtin echo "$@"
	fi
}

is() {
    case $1 in
        quiet)  ((quiet_level > 0));;
      verbose)  ((quiet_level < 0));;
       normal)  ((quiet_level == 0));;
     notquiet)  ((quiet_level <= 0));;
            *)  ((quiet_level == 1));;
    esac
}
cleanup()
{
    cd ~/.gimp
     [[ -e brushes_OFFLINE ]] && mv brushes_OFFLINE brushes
	[[ -e patterns_OFFLINE ]] && mv patterns_OFFLINE patterns
	          trap HUP QUIT EXIT KILL INT
}; 	trap 'cleanup' HUP QUIT EXIT KILL INT
#1


if opts=( `getopt -n $0 -o hvqV -l verbose,help,version,quiet -- "$@"` ); then
	eval set -- "${opts[@]}"
	while [[ $# -ge 0 ]]; do
		curopt=$1
		nextopt=${2-none}
		shift
		# handle --options and -o ptions here
		case $curopt in
			--help|-h)	echo "$help_text"; exit 127;;
			--version|-v) echo "$version_text"; exit 127;;
            --verbose|-V) let quiet_level--;;
			--quiet|-q) let quiet_level++;;
			--) is verbose && echo "done with options";  break;;
			*)	is verbose && echo "handling option: $curopt (next:$nextopt)";;
		esac
	done
	cd ~/.gimp
	if [[ -e brushes_OFFLINE ]] || [[ -e patterns_OFFLINE ]]; then
	    echo "brushes/patterns OFFLINE exist, incomplete run detected, fix before running this program"
    elif [[ -e brushes ]] && [[ -e patterns ]]; then
        echo "ok -- proceeding"
	    mv brushes brushes_OFFLINE
	    mv patterns patterns_OFFLINE
	    cd ~/Documents
	    /usr/bin/gimp "$@"
    else
        echo "cannot find brushes/patterns please create them or make sure they are there"
    fi
	cleanup
	echo "traps after cleanup (if any)..."
	trap
	echo "...(end of listing)"

else
	is notquiet && echo "error, code is $?, exiting with fail"
fi


#1  first trap (in sub) removes traps after cleanup, second initializes the trap to call cleanup if needed
#2  trap cleanup (until confirmed that cleanup does its job always)
