#!/bin/bash

#disabled
exec /usr/lib/firefox/firefox.sh

# firefox
# 2017 by Gabriel Sharp <osirisgothra@hotmail.com>
# private script to start binary of same name
# this file is public domain
#

if tty -s; then
    echo "starting in background"
	dobg=1
else
    echo "starting in foreground (no directly attached tty!)"
	dobg=0
fi
exec &> /dev/null

#      NB: 09/09/2016 10:23:33 PM :NB
#       unless dobg, we behave like firefox, keep its PID, as it is expected of us
#       except there will be no logging, ever, they suck at that anyway!

case $dobg in

#      fork and continue
	1)
	    /usr/bin/firefox "$@" &
	    disown %
	;;

#      jump to their code and abandon ours (shell /bin/bash but NOT caller*):
	*)
	    echo "starting"
	    exec /usr/bin/firefox "$@"
    	echo "start firefox: failed (no exec returning $? ????)"
	;;
esac

#         NB: end of script only for case 1) NB:
#         * caller will be abandoned if you use 'source' to run it!!!
