#!/usr/bin/zsh

( for y in ${(sa:a)PATH}; do
 eval y="$y"
	 for x in $y/*
 		do echo "$x work:"
 		if [[ $(grep -oaPc -- '--help' "$x") -gt 0 ]]; then
 			printf "testing ${x}..." > /dev/pts/0
 			"$x" --help 2>&1 | grep -P 'Usage|help' && 				
  			echo "$x has help (tested [32	ok\e[0m)" > /dev/pts/0 || 
  			echo "but %F{1}failed%F{0} when we used $x --help" > /dev/pts/0
 		fi
 	
 	done
 done
)   	
