#!/usr/bin/perl

use warnings;
use strict;
use v5.20;
use Time::HiRes qw! nanosleep usleep !;

sub sleepms { nanosleep( int(shift) * 1000000 ) };

while (1)
{
	print("more stuff\n");	
	sleepms(1000);
}
