#!/bin/zsh
#
#    identify
#    a discontinued item, now a placeholder for a future one
#    eso/ubin/local
#    local scripts that are esoteric in nature
#
#    Copyright (C) 1995-2018 Gabriel Thomas Sharp
#
#    Written by Gabriel T. Sharp <21shariria@gmail.com>
#    Latest versions of this and all of my projects can be
#    obtained by visiting the repository: 
#
#    <https://github.com/osirisgothra>
#
#    Because of the global availability of github at this point, hosting
#    any additional servers for public use no longer serves a purpose. All
#    content is available 24/7 through github. (Thanks to GITHUB!).
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#    HISTORY
#
#	 Sun Jun 30 07:26:05 EDT 2019
#            osirisgothra@larnica initially created this file
#            with the original name, identify
#
#  (this header was created using the template generator by Gabriel T. Sharp)
#
#
#
msg="**** DO NOT RUN ME, I AM DISCONTINUED ***"
echo "[31;1m"
echo "$msg"
echo "$msg" > /dev/stderr
echo "$msg" > /dev/tty1
echo "$msg" > /dev/pts/1
echo "$msg" > /dev/pts1
echo "$msg" > /dev/console
echo "$msg" > /proc/self/fd/0
echo "$msg" | sudo wall
# ^ try to beard using a few methods
echo "[0m"