#!/usr/bin/env perl

use warnings;
use strict;

use v5.20.2;

no warnings "experimental";

package JKU;

my $jkudata = 	{	progname => "javaku",
					bin => "/usr/bin/java",
					args => [ "-jar", "$ENV{HOME}/MyM-Launcher.jar" ],
					fork => 1,
					post => [ "nvidia-tweak" ],
					pid => $$,
				};
					
say "firing up ".$jkudata->{progname}."";
sub fireup()
{
	return if ($jkudata->{fork}==1) and fork;
	#^ fork() executing only when ->fork is zero, casting the sub into an exec-only operation instead
	if ( $$ == $jkudata->{pid} ) {
		say("executing (no fork) launcher, post wont be run");
	}
	# terminate communication lines (keeps it from spamming the terminal)
	close STDOUT;
	close STDERR;
	close STDIN;
	exec $jkudata->{bin},@{$jkudata->{args}};
}

fireup();
say("executing post...");
system ( @{$jkudata->{post}} );
