#!/bin/perl

use warnings;
use strict;
use v5.20.2;

no warnings 'experimental';

use File::Path::Tiny;

my $jre = findbinary("java")
my %launchers = (	mym	 "~/.mineyourmind/launcher.jar" 
					default	mym )

my $launcher = $launchers->$launchers[default]





