#!/usr/bin/perl
#===============================================================================
#
#         FILE: killer
#
#  DESCRIPTION: 
#
#        FILES: ---
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: Gabriel T. Sharp (osirisgothra), internalinsomnia@gmail.com
# ORGANIZATION: internal insomnia group
#      VERSION: 1.0
#      CREATED: 06/15/2019 07:45:48 PM
#     REVISION: ---
#===============================================================================

use warnings;
use v5.20.1;
use strict;
use Path::Tiny;
use IPC::Open3;




