#!/bin/bash
#
#    mineman
#    minecraft related stuff manager
#    esobin/tiny
#    esoteric projects
#
#    Copyright (C) 1995-2018 Gabriel Thomas Sharp
#
#    Written by Gabriel T. Sharp <21shariria@gmail.com>
#    Latest versions of this and all of my projects can be
#    obtained by visiting the repository: 
#
#    <https://github.com/osirisgothra>
#
#    Because of the global availability of github at this point, hosting
#    any additional servers for public use no longer serves a purpose. All
#    content is available 24/7 through github. (Thanks to GITHUB!).
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#    HISTORY
#
#	 Fri Nov 23 11:30:51 EST 2018
#            osirisgothra@larnica initially created this file
#            with the original name, mineman
#
#  (this header was created using the template generator by Gabriel T. Sharp)
#
#
# TARGET NOTES
#
# target resides in /home/osirisgothra/bin ... [0Gno
# target resides in /home/osirisgothra/bin ... [0Gno
# target resides in /usr/local/sbin ... [0Gno
# target resides in /usr/local/bin ... [0Gno
# target resides in /usr/sbin ... [0Gno
# target resides in /usr/bin ... [0Gno
# target resides in /sbin ... [0Gno
# target resides in /bin ... [0Gno
# target resides in /usr/games ... [0Gno
# target resides in /usr/local/games ... [0Gno
# target resides in ~/bin ... [0Gno
# target resides in /usr/local/gxdwm ... [0Gno
#
declare -gA ERR=( [arg]=140 [val]=141 [fileio]=142 [perm]=143 [syn]=144 [cmderr]=190 [mem]=145 [unk]=146 [sig]=224 [ok]=0 [err]=1 [fatal]=2 [ctrlc]=130 [halt]=147 )
declare -gA CONFIRM_QUIT=( [title]="really quit??" [ok]="yes" [cancel]="cancel" )

#minmax <min> <max> <val> ## values default to zero if not given
minmax()
{
	local -i 	min=$1 max=$2 val=$3
	return $(( (val > max ? max : val) < min ? min : val ))
}

#exit <codename|retval>
exit()
{
	case $# in
		0)	builtin exit $[ERR[ok]]
			;;
		*)  C=$1
			shift
			[[ $# -gt 2 ]] && printf "$(date) exiting (code $C): $@"
			#case $C in
			#	+([0-9]))	# caps min-max are 0-255
			#				C=$(minmax 0 255 $C)
			#				[[ $C -gt 255 ]] && C=255
			#				[[ $C -lt 0   ]] && C=1
			#				builtin exit $C;;
			#	+([a-z]))	builtin exit $[ERR[$C]];;
			#	       *)	builtin exit $[ERR[exitarg];;
			#esac
			;;
	esac
}

#isvar [var1] [...]
is()
{

}

# menu [item array name]
menu()
{
	[[ $# -ne 1 ]] && { echo "FATAL: BAD MENU - (have $#, need 1, and must be array!)"; caller; exit 147; }
	declare -nA _mnu="$1"
}	