#!/bin/bash
if [[ $- =~ i ]]; then
        echo "sourced, setting executable if needed and restarting"
        sudo chmod a+x "$BASH_SOURCE"
        "${BASH_SOURCE[@]}"
else
        declare -a REPLY
        while [[ ${REPLY[0]} != exit ]]; do
                REPLY=( $(dialog --output-fd 1 --inputbox "Enter Search" 0 0) )
                #read -p "Enter Search> " -a REPLY
                case ${REPLY[0]} in
                        # okay for using
                        clear|ls|cd|dir|pwd|whoami)
                                # TODO: untaint:
                                # TODO: protect from shell exploits
                                eval "${REPLY[@]}"                                                                       
                                ;;
                        exit|quit)
                                REPLY=exit
                                ;;
                        *)
                                echo "submitting query..."
                                T "${REPLY[@]}" &> /dev/null & disown
                                echo -e "\e[1;33m-- another window is opening --\e[0m"
                                ;;
                esac
        done
fi

