#!/bin/zsh

declare -g target="/usr/bin/man"
# TODO: find something better [[ $TERM == linux ]] && export MANPAGER="vim -M +MANPAGER -"

function main()
{
	case $1 in delegate_me) shift; exec $target "$@";; esac
	$target "$@"

}

if (($# == 1)) && [[ $1 =~ '^[^()]+$' ]]
	then
		main "$1"
	else
		main delegate_me "$@"
fi