#!/bin/zsh
# vim: ft=zsh:sw=2:noet:ts=2:fen:foldclose=all:foldopen=all:fdm=marker:fmr=#{,#}:foldlevel=1:ruler:ls=2:backspace=2
#    menu
#    dialog wrapper for quick menu system creation
#    mini
#    esoteric projects
#
#    Copyright (C) 1995-2018 Gabriel Thomas Sharp
#
#    Written by Gabriel T. Sharp <21shariria@gmail.com>
#    Latest versions of this and all of my projects can be
#    obtained by visiting the repository: 
#
#    <https://github.com/osirisgothra>
#
#    Because of the global availability of github at this point, hosting
#    any additional servers for public use no longer serves a purpose. All
#    content is available 24/7 through github. (Thanks to GITHUB!).
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#  HISTORY
#
#	 	Mon Feb 18 10:24:31 EST 2019
#            osirisgothra@larnica initially created this file
#            with the original name, menu
#
#  	(this header was created using the template generator by Gabriel T. Sharp)
#
# REQUIRED PROGRAMS
#
#		 Filename: cdialog, dialog
# 	 Filedesc: "ComeOn Dialog!" 
# 	 Packages: gnu-linux,dialog,libncurses
# 	 Packaged: vendor-packaged at time of distribution
#    Verscode: 1.2-20150528
#

#
# TARGET NOTES
#
# dialog <options> { --and-widget <options> }
#   [--create-rc "file"]
#   [--ascii-lines] [--aspect <ratio>] [--backtitle <backtitle>] [--beep] [--beep-after] [--begin <y> <x>] [--cancel-label <str>] 
#   [--clear] [--colors] [--column-separator <str>] [--cr-wrap] [--date-format <str>] [--default-button <str>] [--default-item <str>] [--defaultno]
#   [--exit-label <str>] [--extra-button] [--extra-label <str>]
#   [--help-button] [--help-label <str>] [--help-status] [--help-tags]
#   [--hfile <str>] [--hline <str>] [--ignore] [--input-fd <fd>]
#   [--insecure] [--item-help] [--keep-tite] [--keep-window] [--last-key]
#   [--max-input <n>] [--no-cancel] [--no-collapse] [--no-cr-wrap]
#   [--no-items] [--no-kill] [--no-label <str>] [--no-lines] [--no-mouse]
#   [--no-nl-expand] [--no-ok] [--no-shadow] [--no-tags] [--nook]
#   [--ok-label <str>] [--output-fd <fd>] [--output-separator <str>]
#   [--print-maxsize] [--print-size] [--print-version] [--quoted]
#   [--scrollbar] [--separate-output] [--separate-widget <str>] [--shadow]
#   [--single-quoted] [--size-err] [--sleep <secs>] [--stderr] [--stdout]
#   [--tab-correct] [--tab-len <n>] [--time-format <str>] [--timeout <secs>]
#   [--title <title>] [--trace <file>] [--trim] [--version] [--visit-items]
#   [--yes-label <str>]
#{ Box options:
#   --buildlist    <text> <height> <width> <tag1> <item1> <status1>...
#   --calendar     <text> <height> <width> <day> <month> <year>
#   --checklist    <text> <height> <width> <list height> <tag1> <item1> <status1>...
#   --dselect      <directory> <height> <width>
#   --editbox      <file> <height> <width>
#   --form         <text> <height> <width> <form height> <label1> <l_y1> <l_x1> <item1> <i_y1> <i_x1> <flen1> <ilen1>...
#   --fselect      <filepath> <height> <width>
#   --gauge        <text> <height> <width> [<percent>]
#   --infobox      <text> <height> <width>
#   --inputbox     <text> <height> <width> [<init>]
#   --inputmenu    <text> <height> <width> <menu height> <tag1> <item1>...
#   --menu         <text> <height> <width> <menu height> <tag1> <item1>...
#   --mixedform    <text> <height> <width> <form height> <label1> <l_y1> <l_x1> <item1> <i_y1> <i_x1> <flen1> <ilen1> <itype>...
#   --mixedgauge   <text> <height> <width> <percent> <tag1> <item1>...
#   --msgbox       <text> <height> <width>
#   --passwordbox  <text> <height> <width> [<init>]
#   --passwordform <text> <height> <width> <form height> <label1> <l_y1> <l_x1> <item1> <i_y1> <i_x1> <flen1> <ilen1>...
#   --pause        <text> <height> <width> <seconds>
#   --prgbox       <text> <command> <height> <width>
#   --programbox   <text> <height> <width>
#   --progressbox  <text> <height> <width>
#   --radiolist    <text> <height> <width> <list height> <tag1> <item1> <status1>...
#   --rangebox     <text> <height> <width> <min-value> <max-value> <default-value>
#   --tailbox      <file> <height> <width>
#   --tailboxbg    <file> <height> <width>
#   --textbox      <file> <height> <width>
#   --timebox      <text> <height> <width> <hour> <minute> <second>
#   --treeview     <text> <height> <width> <list-height> <tag1> <item1> <status1> <depth1>...
#   --yesno        <text> <height> <width>
#} 
# Auto-size with height and width = 0. Maximize with height and width = -1.
# Global-auto-size if also menu_height/list_height = 0.
#

# syntax: menu [kind] [title] [item(s)]

#mnu_setopts [item] [value]
#item:
#  
function mnu_setopts()
{
	local item=${1-none}
	local value=${2-empty}

}

#yn [text] | 0=yes 1=no brk=>2
function mnu_yn()
{
	${DEP[@]} $(xlatargs yn)
}

#buildlist    <text> <height> <width> <tag1> <item1> <status1>...                                                               
function mnu_buildlist()
{
	${DEP[@]} $(xlatargs buildlist) 
}

#calendar     <text> <height> <width> <day> <month> <year>                                                                      
function mnu_calendar()
{
	${DEP[@]} $(xlatargs calendar)
}

#checklist    <text> <height> <width> <list height> <tag1> <item1> <status1>...                                                 
function mnu_checklist()
{
	${DEP[@]} $(xlatargs checklist)
}

#dselect      <directory> <height> <width>                                                                                      
function mnu_dselect()
{
	${DEP[@]} $(xlatargs dselect)
}

#editbox      <file> <height> <width>                                                                                           
function mnu_editbox()
{
	${DEP[@]} $(xlatargs editbox)
}

#form         <text> <height> <width> <form height> <label1> <l_y1> <l_x1> <item1> <i_y1> <i_x1> <flen1> <ilen1>...             
function mnu_form()
{
	${DEP[@]} $(xlatargs form)
}

#fselect      <filepath> <height> <width>   
function mnu_fselect()
{
	${DEP[@]} $(xlatargs fselect)
}

#gauge        <text> <height> <width> [<percent>]                                                                               
function mnu_gauge()
{
	${DEP[@]} $(xlatargs gauge)
}

#infobox      <text> <height> <width>                                                                                           
function mnu_infobox()
{
	${DEP[@]} $(xlatargs infobox)
}

#inputbox     <text> <height> <width> [<init>]                                                                                  
function mnu_inputbox()
{
	${DEP[@]} $(xlatargs inputbox)
}

#inputmenu    <text> <height> <width> <menu height> <tag1> <item1>...                                                           
function mnu_inputmenu()
{
	${DEP[@]} $(xlatargs inputmenu)
}

#menu         <text> <height> <width> <menu height> <tag1> <item1>...                                                           
function mnu_menu()
{
	${DEP[@]} $(xlatargs menu)
}

#mixedform    <text> <height> <width> <form height> <label1> <l_y1> <l_x1> <item1> <i_y1> <i_x1> <flen1> <ilen1> <itype>...     
function mnu_mixedform()
{
	${DEP[@]} $(xlatargs mixedform)
}

#mixedgauge   <text> <height> <width> <percent> <tag1> <item1>...                                                               
function mnu_mixedgauge()
{
	${DEP[@]} $(xlatargs mixedgauge)
}

#msgbox       <text> <height> <width>                                                                                           
function mnu_msgbox()
{
	${DEP[@]} $(xlatargs msgbox)
}

#passwordbox  <text> <height> <width> [<init>]                                                                                  
function mnu_passwordbox()
{
	${DEP[@]} $(xlatargs passwordbox)
}

#passwordform <text> <height> <width> <form height> <label1> <l_y1> <l_x1> <item1> <i_y1> <i_x1> <flen1> <ilen1>...             
function mnu_passwordform()
{
	${DEP[@]} $(xlatargs passwordform)
}

#pause        <text> <height> <width> <seconds>                                                                                 
function mnu_pause()
{
	${DEP[@]} $(xlatargs pause)
}

#prgbox       <text> <command> <height> <width>                                                                                 
function mnu_prgbox()
{
	${DEP[@]} $(xlatargs prgbox)
}

#programbox   <text> <height> <width>                                                                                           
function mnu_programbox()
{
	${DEP[@]} $(xlatargs programbox)
}

#progressbox  <text> <height> <width>                                                                                           
function mnu_progressbox()
{
	${DEP[@]} $(xlatargs progressbox)
}

#radiolist    <text> <height> <width> <list height> <tag1> <item1> <status1>...                                                 
function mnu_radiolist()
{
	${DEP[@]} $(xlatargs radiolist)
}

#rangebox     <text> <height> <width> <min-value> <max-value> <default-value>                                                   
function mnu_rangebox()
{
	${DEP[@]} $(xlatargs rangebox)
}

#tailbox      <file> <height> <width>                                                                                           
function mnu_tailbox()
{
	${DEP[@]} $(xlatargs tailbox)
}

#tailboxbg    <file> <height> <width>                                                                                           
function mnu_tailboxbg()
{
	${DEP[@]} $(xlatargs tailboxbg)
}

#textbox      <file> <height> <width>                                                                                           
function mnu_textbox()
{
	${DEP[@]} $(xlatargs textbox)
}

#timebox      <text> <height> <width> <hour> <minute> <second>                                                                  
function mnu_timebox()
{
	${DEP[@]} $(xlatargs timebox)
}

#treeview     <text> <height> <width> <list-height> <tag1> <item1> <status1> <depth1>...                                        
function mnu_treeview()
{
	${DEP[@]} $(xlatargs treeview)
}

#yesno        <text> <height> <width>                                                                                           
function mnu_yesno()
{
	${DEP[@]} $(xlatargs yesno)
}

