#!/bin/zsh

echo() { print -P $@; }
indent() {
    perrow=${2-0}
    [[ $# -ne 2 ]] && echo "indent() needs exactly 2 arguments (not $#)" && exit 127    
    rpos=0
    while read r; do
        if ((rpos == 0)) {
            for ((n=0;n<${1-0};n++)) { printf " "; }
        }
        # add barrier for % signs
        printf -- "${r//\%/%%}"
        if ((rpos >= perrow)); then
            rpos=0
            printf "\n"
        else
            printf "\t"
            rpos=$(( rpos + 1 ))
        fi

    done
}
echo "Memory"
cat /proc/meminfo | grep '^Mem' | hi "[0-9]+" "[kK][bB]" "Mem[A-Z][a-z]+" | indent 4 2
echo

echo "Disk"
df --type=ext4 --type=iso9660 --type=vfat --type=nfs -h --total | hi '%' ':' '=' '(Filesystem|Mounted [Oo]n|Used|Avail|Size|Use%)' '\b[MmGgkK][bB]?\b' | indent 4 0
echo
# set these to whatever they are on your system
declare -gA names=(     temp1           "Mainboard"
                        temp2           "CPU Thermistor"
                        temp3           "Southbridge"
                        fan1            "CPU FAN"
                        fan2            "Chassis Fan"
                        fan3            "PSU/GPU Fan"
                 )
echo "Fan/Temp Sensors"
eval declare -gA se=\(\ `sensors | tail -n+2 | tr -d ':' | head -n-1 | awk '{ print("\""$1"\" \""$2"\""); }'`\ \)
{ for x in ${(k)se}; do
    if [[ $x =~ "(temp|fan)" ]]; then
        if [[ ${names[$x]} ]]; then
            name="${names[$x]}($x)"
        else
            name=$x
        fi
        if [[ $x =~ fan ]] && [[ ${se[$x]} == 0 ]]; then
            true skip fans at zero RPM until end
            zfans+=( $name )
        else
            echo "%B$name%b: %F{2}${se[$x]}%f"
       fi
    fi
done
if [[ -n $zfans ]]; then
    echo "\nWarning, These Fans at Zero RPMs: $zfans"
fi
} | indent 4 2
echo