#!/usr/bin/env perl

eval 'echo -e "[1;31;5m********************************\n[5mperl binary must run this script\n********************************[0m"; return' if 0;

use warnings;
use strict;
use v5.20.2;
no warnings 'experimental';
use feature 'signatures';


# read in ini

