#!/usr/bin/perl
#
#    <fname>
#    <fdesc>
#    <pname>
#	 <pdesc>
#
#    Copyright (C) 1995-20?? Gabriel Thomas Sharp
#
#    Written by Gabriel T. Sharp <21shariria@gmail.com>
#    Latest versions of this and all of my projects can be
#    obtained by visiting the repository: 
#
#    <https://github.com/osirisgothra>
#
#      Because of the global availability of github at this point, hosting
#    any additional servers for public use no longer serves a purpose. All
#    content is available 24/7 through github. (Thanks to GITHUB!).
#
#      This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#      This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#      You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#    HISTORY
#
#	 <date>
#            say hello to <fname>, <fdesc>!!
#            osirisgothra@larnica initially created this file
#            with the original name, <fname>. It was then
#            added to the project, <pname>, a project that
#            is described by <pdesc>.
#
#    FOOTNOTES
#
#      this header was created using the template generator by Gabriel T. Sharp)
#  
#
#

use warnings;
use v5.18;
use strict;
use Getopt::Long::Descriptive; # opt|shortchar[kind] (kind is =s[tr],=i[nt], or none)
use English; 				   # used for PROGRAM_NAME and others

no warnings "experimental";

my $prog = $PROGRAM_NAME // exit("could not determine program name $! $?");


my ($opt, $usage) = describe_options(
        '$0 %o <some-arg> file',
        [ 'no-dialog', "dont use dialog to show log", { required => 1  } ],
        [ 'no-follow',   "do not follow the log, just show it",   { default  => 79 } ],
        [],
        [ 'verbose|v',  "print extra stuff"            ],
        [ 'help',       "print usage message and exit" ],
      );

print($usage->text), exit if $opt->help;





my $name = $PROGRAM_NAME;


