#!/usr/bin/perl
#
#   qv
#   quick and dirty image viewer
#   requires Gtk2 bindings
#   does not require Webkit, however
#

use v5.20.2;
use warnings;
use strict;
use Path::Tiny qw(path);
use Gtk2 -init;
use Getopt::Long::Descriptive;
use File::MimeInfo;                 # no magic
# make local copies of (these get changed by G::L::Descriptive)
my $argc = $#ARGV;
my @argv = @ARGV;

  use Getopt::Long::Descriptive;

  my ($opt, $usage) = describe_options(
    'qv %o <image1 ...>\nqv %o <text1 ...>',
    [],
    [ 'man|m', "manpage mode" ],
    [ 'verbose|v',  "print extra stuff"            ],
    [ 'help',       "print usage message and exit", { shortcircuit => 1 } ],
  );

  print($usage->text), exit if $opt->help;

my $w=new Gtk2::Window( "GTK_WINDOW_TOPLEVEL" );
$w->set_title('Quick Viewer ' . $argc . ' Items Opened');
$w->signal_connect('delete_event' => sub { Gtk2->main_quit; });
$w->set_border_width(3);
$w->set_position('center_always');

my $v=new Gtk2::VBox();
my $s=new Gtk2::ScrolledWindow();
my $i=undef;
my $n=undef;
for $n (@ARGV)
{
    $n = path($n);
    no warnings 'experimental';    
    unless ( $opt->man )
    {
        if ( -r $n )  
        {
        
            given(mimetype($n))
            {
                # wrap images into an HBox that has
                # a label with some markup in it, and the image itself next door to it (to the left like file managers do)
                when (/image/) {
                    my $l = new Gtk2::Label();
                    my $h = new Gtk2::HBox();                   
                    $h->set_size_request(16,16);                    
                    $l->set_use_markup(1); # switch to pseudo-ml (pango) format in text
                    $l->set_markup



                    ("<a href=\"".$n->realpath()."\">" . $n->basename() . "</a>");  
                    # anchor a URL so user can access the whole link
                    # note: pango defaults to not letting clicks happen, and we only want the copy link function
                    # (because I hate programs that open a browser and so on, id rather it copy the link, thats what
                    # happens here, right click the link and you get a menu and choose it from there, as it should be)
                    
                    
                                        
                    $i= new Gtk2::Image();
                    $i->set_from_file($n);    
                    $h->add($i);        # add image
                    $h->add($l);        # add text describing image
                    $v->add($h);
                }
                default {
                    $i = new Gtk2::TextView();
                    $b = new Gtk2::TextBuffer();
                    $i->set_buffer($b);
                    $i->set_size_request(50,50);
                    $b->set_text($n->slurp());
                    $v->add($i);
                }
            }
        }
    }
    else
    {
        $i = new Gtk2::TextView();
        $b = new Gtk2::TextBuffer();
        $i->modify_font(Gtk2::Pango::FontDescription->from_string("Liberation Mono 10"));
        
        $i->set_buffer($b);
        $i->set_size_request(16,16);
        my $text = `man -7 $n |cat`;
        $b->set_text($text);
        $v->add($i);
    }            
        
}    
$s->add_with_viewport($v);
$w->add($s);
# this determines the size of the entire window only
$w->set_default_size(640,480);
$w->show_all();
Gtk2->main();


