#!/usr/bin/perl 
#===============================================================================
#
#         FILE:  runlinkasroot
#
#        USAGE:  ./runlinkasroot  
#
#  DESCRIPTION: Run program as root user via sudo 
#
#      OPTIONS:  ---
# REQUIREMENTS:  ---
#         BUGS:  ---
#        NOTES:  ---
#       AUTHOR:  Gabriel Thomas Sharp (gt), osirisgothra@hotmail.com
#      COMPANY:  Paradisim NCNP
#      VERSION:  1.0
#      CREATED:  07/24/2020 11:20:57 AM
#     REVISION:  ---
#===============================================================================

use strict;
use warnings;


#!/usr/bin/perl

