#!/bin/zsh

typeset -i cursorsize=32
zmodload zsh/mapfile
pushd /usr/share/icons
find -L -maxdepth 2 -iname 'cursors' -exec find -L '{}' ';' > /tmp/cursors.txt
typeset -a x=( ${(@f)mapfile[/tmp/cursors.txt]} )
typeset -a f=()
for y in $x; do f+=( "$y" "$(basename $y)" ); done
while true; do
	if result=$(dialog --output-fd 1 --menu c 52 82 42 $f); then
		xsetroot -xcf "$result" "$cursorsize"
	else
		echo "exiting"
		break
	fi
done
popd