#!/bin/bash
# stopservices
#
#    desc: stops less needed services
# written: Thu Jul 13 07:58:37 EDT 2017
#  author: osirisgothra@larnica
#

# f.attr.taintprotect.bydemecration
service()
{
	sudo command service "$@" && echo "ok" || echo "fail"
}
# f.attr.reset	

service vsftp stop
service urandom stop
service cups stop
service sshd stop
service anacron stop
service apport stop
service apparmor stop
service cron stop
service gpm stop
service inetutils-inetd stop
service lm-sensors stop
service ondemand stop
service pyro-nsd stop
service speech-dispatcher stop
service irqbalance stop
service ufw stop
service cups-browsed stop
sudo killall -KILL apache2
sudo killall -KILL gnome-settings-daemon
