#!/bin/zsh

zmodload zsh/curses
use aliases
tm_aliases=( init end addwin delwin refresh touch move clear
			 position char string border attr bg scroll input
			 mouse timeout querychar )

mainwin="WINDOW"
declare -g progname="$0"
# zsh/curses
#	init
#	end
#   =====================================================
#	addwin targetwin width height column line [ parent ]
#	delwin targetwin
#   =====================================================
#	refresh [ targetwin ... ]
#	touch targetwin ...
#	move targetwin y x
#	clear targetwin [ redraw | eol | bot ]
#	position targetwin array
#	char targetwin character
#	string targetwin string
#	border targetwin border
#	attr targetwin [ [+|-]attribute | fg_col/bg_col ] [...]
#	bg targetwin [ [+|-]attribute | fg_col/bg_col | @char ] [...]
#	scroll targetwin [ on | off | [+|-]lines ]
#	input targetwin [ param [ kparam [ mparam ] ] ]
#	mouse [ delay num | [+|-]motion ]
#	timeout targetwin intval
#	querychar targetwin [ param ]

curses_main()
{
	addwin MAIN 1 1 10
	attr MAIN +bold red blue
	border MAIN single
	refresh MAIN
	sleep 5
	

}

main()
{
	for ta in $tm_aliases; do
		eval "alias $ta='zcurses $ta'"
	done
	init
	{
		curses_main "$@"
	}
	end
}

main "$@"

