#!/bin/zsh

declare -x debugging=0
declare -agx PAGES=( )
declare -agx TOPICS=( )
#set -x
IFS=$'\n'
for w; do
	eval "declare -ga TOPIC_${w}=( )"

	for y in $(command man "$w" | grep --color=never '^([A-Z]+( |$))+$' -Po); do
		eval "TOPIC_${w}+=( '$y' )"
	done
	((debugging)) && eval declare -p TOPIC_${w}
	TOPICS+=( "$w" )
done

#set +x
function menu()
{
	declare -ag TAGS=(  )
	MENUTEXT="$1"
	shift
	# args: MENUTEXT item(s)
	for i; do
		((debugging)) && echo "adding $i x2"
		TAGS+=( "$i" )
		TAGS+=( "$i" )
	done
	sleep 1
	declare -gx RESPONSE=`dialog --no-tags --ok-label Select --cancel-label Exit --output-fd 1 --backtitle "Topics Available" --menu "$MENUTEXT" 0 0 $# "${TAGS[@]}"`

}
menu "Select a Topic" "${TOPICS[@]}"
eval menu "Select Subtopic" "\${TOPIC_${RESPONSE}[@]}"
echo $RESPONSE

set +x
