#!/bin/sh
#
#    xhtop
#    A Xhtop Program
#    The Xhtop Project / eso-bin
#    A Project That Gloriously Houses Xhtop / esoteric projects and scripts
#
#    Copyright (C) 1995-2018 Gabriel Thomas Sharp
#
#    Written by Gabriel T. Sharp <21shariria@gmail.com>
#    Latest versions of this and all of my projects can be
#    obtained by visiting the repository: 
#
#    <https://github.com/osirisgothra>
#
#    Because of the global availability of github at this point, hosting
#    any additional servers for public use no longer serves a purpose. All
#    content is available 24/7 through github. (Thanks to GITHUB!).
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#    TODO
#		add more things to this script, plan for the future
#
#    HISTORY
#
#    PLEASE NOTE!
#
#    THIS SCRIPT IS NOT BASH, IT IS SH (/bin/sh) DO NOT USE BASH DIRECTIVES HERE
#
#	 Sun Oct  7 09:32:10 EDT 2018
#            osirisgothra@larnica initially created this file
#            with the original name, xhtop
#
#  (this header was created using the template generator by Gabriel T. Sharp)
#
#
exec 2>/dev/null 1>/dev/null
exec /usr/bin/stterm -e /usr/bin/htop
