#!/bin/zsh
#
#    xy
#    learn x in y downloader/displayer in CLI
#    mini
#    eso/ubin-local
#
#    Copyright (C) 1995-2018 Gabriel Thomas Sharp
#
#    Written by Gabriel T. Sharp <21shariria@gmail.com>
#    Latest versions of this and all of my projects can be
#    obtained by visiting the repository: 
#
#    <https://github.com/osirisgothra>
#
#    Because of the global availability of github at this point, hosting
#    any additional servers for public use no longer serves a purpose. All
#    content is available 24/7 through github. (Thanks to GITHUB!).
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#    HISTORY
#
#	 Tue 13 Oct 2020 11:35:00 AM EDT
#            osirisgothra@ initially created this file
#            with the original name, xy
#
# TARGET NOTES
#
# 	EXECUTIVE STATE CHANGES
#		marking single existing file executable
#			- mode of 'xy' changed to u+rwx/og+rx.. []
#		completed (0)
# 	ARGUMENTUAL ANALYSIS
#       remaining arguments:
#			no arguments to list
#       disposition:
#			4 were used during execution of template
#   		0 were extra and/or unexpected
# 	TEMPLATE SUMMARY OF GENERATION
#	     outcome: good
#	     errors: 0
# 	FINAL NOTE
#	     template program under renovation
#        you should REMOVE the TARGET NOTES section once youve reviewed this!
#		 (Tue 13 Oct 2020 11:35:00 AM EDT): osirisgothra ignored the final note and left this behind for
#		           the user(s) to see, how embarassed I am for the author!
#
#
#  (this template+header was created using the template generator by Gabriel T. Sharp)
#




# Get Options from Command Line for xy 

declare -ga opts
declare -gi quiet_level=0
declare -g version_text="$(tput setaf 124)xy$(tput sgr0) Version 1.0 (C)2020 Gabriel T. Sharp, Licensed under GNU LGPL3 at https://gpl.gnu.org/gpl3.html"
declare -g help_text="xy
learn x in y downloader/displayer in CLI

SYNTAX

	xy [OPTIONS] ARGUMENTS

OPTIONS
	--text -t   force plain-text processing in all cases
    --html -H   force conversion to HTML in most cases* (overrides CONVERTER environment variable)
    --file -f   use the file link in the page, if any (some pages may not have this, so it is not the default)
	--help -h	show this help text
 --version -v   display version information and exit (also shows license info)
   --quiet -q   increase quiet level by one (quiet level is always zero if left alone)

ARGUMENTS

	STRING		A readable string, it must not contain any unreprintable characters.
				this string will be used to locate the document (ie, 'perl')
*NOTES

  1) The HTML conversion is only possible when the text2html(1) binary is installed
     on the target host. If it is not installed, CONVERTER=txt will be forced
     even if you have -H and/or have set CONVERTER yourself. Usually this is
     installed on most mid-sized and modern linux builds.
  2) BEAR IN MIND that if you use the -f option, the string you provide must
     be the filename, not the language identifier. For example, perl works for
     looking up the perl page, but to see the code page you would need to
     specify 'learnperl.pl'. To get a complete list of files on the server
     you should visit their website (see below).

PORTING

	No information about porting has been submitted as of yet.

EXAMPLE USAGE

	show perl page: xy perl
	show python page: xy python3
		and so on...

LEARNXINY

	The author of this tool has no affiliation with the website. The content
	from their website is subject to THEIR LICENSES, and you must agree to
    them in order to download and view the content provided by them.

	Credit for ALL the documents are listed on the website, and none of them
    are me, so please give credit where it is due and adhere to their licenses
	and rules where and when they apply. Those rules and licenses can be found
    on the webpage(s) listed on each page or on the homepage, if not specified
    otherwise. Lastly, if you are unsure, please write them to find out what
    you can and cant do with this documentation. Err on caution!

	Visit http://www.learnxiny.com for a list of available languages!

LICENSE

	GNU LGPL3 is available in full at the GNU GPL website, or through the google voice command 'show me GNU LGPL VERSION 3'

"
extraprefix=""
echo() {
	if [[ $quiet_level -gt 0 ]]; then
		return 127
	else
		builtin echo "$@"
	fi
}

if opts=( `getopt -n $0 -o Htfhvq -l text,html,file,help,version,quiet -- "$@"` ); then
	eval set -- "${opts[@]}"
	while [[ $# -ge 0 ]]; do
		curopt=$1
		nextopt=${2-none}
		shift
		# handle --options and -o ptions here
		case $curopt in
			--html|-m) CONVERTER=html;;
			--text|-t) CONVERTER=txt;;
			--help|-h)	echo "$help_text"; exit 127;;
			--version|-v) echo "$version_text"; exit 127;;
			--quiet|-q) let quiet_level++;;
			--file|-f) extraprefix="files/";;	# get from files instead
			--) echo "done with options"; break;;
			*)	echo "handling option: $curopt (next:$nextopt)";;
		esac
	done
else
	echo "error, code is $?, exiting with fail"
fi

# functions

function ghtml()
{
	wget --no-check-certificate https://www.learnxinyminutes.com/docs/${extraprefix}"$*" -o /tmp/last-xy-$USER.log -O-; 
}
function iconverter()
{
	# use plain text if dealing with -f
	if [[ -n $extraprefix ]]; then
		CONVERTER=txt
	fi

	# useless use of cat i know: it is a placeholder value
	# until another processor is replaced with it, if ever needed
	# this makes converting in the future much easier:
	case ${CONVERTER-html} in
		html)	[[ -x /usr/bin/html2text ]] && 		{

					/usr/bin/html2text

													} || {

					/usr/bin/cat

				}
				;;
		*)		/usr/bin/cat;;
	esac

}
function ipager()
{
	iconverter | less -P "?f%f .?m(%T %i of %m) .?ltlines %lt-%lb?L/%L. ."
}

## codestate: $@ populated with plain words supplied by user

# deal with each query at a time
for lang; do
	ghtml $lang | ipager
done




