#!/usr/bin/perl
use v5.20;
use warnings;
use strict;

# drop args into xprop
my $itemstr = join("",`xprop @ARGV`);
#my @cmdstr = qx ! xprop -root -len 80 | grep -P '=\\s*\\S+.*' |  tr '=:' '\\n'  | sed -r 's/^\\s*//g' !;
#print "ITEM:$_" for @cmdstr;
#my @cmdout = `@cmdstr`;
die("nothing to show!") unless length($itemstr) > 0;
exit(0) if system('/usr/bin/zenity','--info','--text',$itemstr,'--title','zprop output');
#system('/usr/bin/zenity','--list','--column','attribute','--column','value',@cmdstr);
