#!/usr/bin/zsh
for filename; do
	( zsh -n  $filename  2>&1 | perl -wne '/(^[^:]+ ?)(:)?([0-9]+ ?)?(:)?([0-9]+ )?(.*)/; print "zsh:" . ( $3 // "1" ) . ":" . ( $5 // "1" ) . ": $6";' | tr -s ' '; echo  ) > /dev/stderr
done